export const Constant = {
  // Account
  ACCOUNT_KIND_ADMIN: 1,
  ACCOUNT_KIND_EMPLOYEE: 2,
  ACCOUNT_KIND_USER: 3,

  // Status
  STATUS_PENDING: 0,
  STATUS_ACTIVE: 1,
  STATUS_LOCK: -1,
  STATUS_DELETED: -2,

  // Group
  GROUP_KIND_ADMIN: 1,
  GROUP_KIND_USER: 2,
  GROUP_NAME_USER: 'Role User',

  // Product Variant
  PRODUCT_VARIANT_CONDITION_NEW: 1,
  PRODUCT_VARIANT_CONDITION_OLD: 2,
  PRODUCT_VARIANT_FORMAT_HARD_COVER: 1,
  PRODUCT_VARIANT_FORMAT_PAPER_BACK: 2,

  // Contributor
  CONTRIBUTOR_KIND_AUTHOR: 1,
  CONTRIBUTOR_KIND_TRANSLATOR: 2,

  // Gender
  GENDER_MALE: 1,
  GENDER_FEMALE: 2,
  GENDER_OTHER: 3,

  // Order status
  ORDER_STATUS_WAITING: 0,
  ORDER_STATUS_WAITING_CONFIRMATION: 1,
  ORDER_STATUS_CONFIRMED: 2,
  ORDER_STATUS_PACKING: 3,
  ORDER_STATUS_SHIPPING: 4,
  ORDER_STATUS_COMPLETE: 5,
  ORDER_STATUS_CANCELED: 6,
  ORDER_STATUS_REQUEST_REFUND: 7,
  ORDER_STATUS_REFUNDED: 8,

  // CMD update status order
  CMD_CONFIRM_ORDER: 'CMD_CONFIRM_ORDER', // WAITING_CONFIRMATION -> CONFIRMED
  CMD_START_PACKING: 'CMD_START_PACKING', // CONFIRMED -> PACKING
  CMD_START_SHIPPING: 'CMD_START_SHIPPING', // PACKING -> SHIPPING
  CMD_CONFIRM_REFUNDED: 'CMD_CONFIRM_REFUNDED', // REQUEST REFUND -> REFUNDED

  // Payment method
  PAYMENT_METHOD_COD: 1,
  PAYMENT_METHOD_VNPAY: 2,

  // Coupoun
  COUPON_KIND_DISCOUNT: 1,
  COUPON_KIND_FREESHIP: 2,
  COUPON_TYPE_FIXED: 1,
  COUPON_TYPE_PERCENTAGE: 2
} as const;

export const fileFolders = {
  ['1']: 'systems',
  ['2']: 'avatars'
};

export const OrderTransitions: Record<string, { from: number[]; to: number }> =
  {
    [Constant.CMD_CONFIRM_ORDER]: {
      from: [Constant.ORDER_STATUS_WAITING_CONFIRMATION],
      to: Constant.ORDER_STATUS_CONFIRMED
    },
    [Constant.CMD_START_PACKING]: {
      from: [Constant.ORDER_STATUS_CONFIRMED],
      to: Constant.ORDER_STATUS_PACKING
    },
    [Constant.CMD_START_SHIPPING]: {
      from: [Constant.ORDER_STATUS_PACKING],
      to: Constant.ORDER_STATUS_SHIPPING
    },
    [Constant.CMD_CONFIRM_REFUNDED]: {
      from: [Constant.ORDER_STATUS_REQUEST_REFUND],
      to: Constant.ORDER_STATUS_REFUNDED
    }
  };
