export const ErrorCode = {
  // Auth
  AUTH_ERROR_PASSWORD_MISMATCH: 'ERROR-AUTH-0000',
  AUTH_ERROR_OTP_INVALID_OR_EXPIRED: 'ERROR-AUTH-0001',
  AUTH_ERROR_UNAUTHORIZED: 'ERROR-AUTH-0002',

  // Account
  ACCOUNT_ERROR_NOT_FOUND: 'ERROR-ACCOUNT-0000',
  ACCOUNT_ERROR_EMAIL_EXISTED: 'ERROR-ACCOUNT-0001',
  ACCOUNT_ERROR_INVALID_PASSWORD: 'ERROR-ACCOUNT-0002',
  ACCOUNT_ERROR_PHONE_EXISTED: 'ERROR-ACCOUNT-0003',
  ACCOUNT_ERROR_NOT_ALLOW_DELETE: 'ERROR-ACCOUNT-0004',
  ACCOUNT_ERROR_EMAIL_INVALID: 'ERROR-ACCOUNT-0005',

  // Category
  CATEGORY_ERROR_NOT_FOUND: 'ERROR-CATEGORY-0000',
  CATEGORY_ERROR_NAME_EXISTED: 'ERROR-CATEGORY-0001',
  CATEGORY_ERROR_INVALID_REQUEST: 'ERROR_CATEGORY_0002',
  CATEGORY_ERROR_IN_USE: 'ERROR_CATEGORY_0003',

  // Permission
  PERMISSION_ERROR_NOT_FOUND: 'ERROR-PERMISSION-0000',
  PERMISSION_ERROR_NAME_EXISTS: 'ERROR-PERMISSION-0001',
  PERMISSION_ERROR_CODE_EXISTS: 'ERROR-PERMISSION-0002',

  // Group
  GROUP_ERROR_NOT_FOUND: 'ERROR-GROUP-0000',
  GROUP_ERROR_NAME_EXISTS: 'ERROR-GROUP-0001',
  GROUP_ERROR_IN_USED: 'ERROR-GROUP-0002',

  // Product
  PRODUCT_ERROR_NOT_FOUND: 'ERROR-PRODUCT-0000',

  // File
  FILE_ERROR_KIND_REQUIRED: 'ERROR-FILE-0000',
  FILE_ERROR_KIND_INVALID: 'ERROR-FILE-0001',

  // Product image
  PRODUCT_IMAGE_ERROR_NOT_FOUND: 'ERROR-PRODUCT-IMAGE-0000',
  PRODUCT_IMAGE_ERROR_INVALID_REQUEST: 'ERROR-PRODUCT-IMAGE-0001',

  // Permission Group
  PERMISSION_GROUP_ERROR_NOT_FOUND: 'ERROR-PERMISSION-GROUP-0000',
  PERMISSION_GROUP_ERROR_NAME_EXISTS: 'ERROR-PERMISSION-GROUP-0001',

  // Cart
  CART_ERROR_NOT_FOUND: 'ERROR-CART-0000',

  // Cart Item
  CART_ITEM_ERROR_NOT_FOUND: 'ERROR-CART-ITEM-0000',

  //Publisher
  PUBLISHER_ERROR_NOT_FOUND: 'ERROR-PUBLISHER-0000',

  // Product Variant
  PRODUCT_VARIANT_ERROR_NOT_FOUND: 'ERROR-PRODUCT-VARIANT-0000',
  PRODUCT_VARIANT_ERROR_EXISTED: 'ERROR-PRODUCT-VARIANT-0001',
  PRODUCT_VARIANT_ERROR_OUT_OF_STOCK: 'ERROR-PRODUCT-VARIANT-0002',

  // Contributor
  CONTRIBUTOR_ERROR_NOT_FOUND: 'ERROR-CONTRIBUTOR-0000',
  CONTRIBUTOR_ERROR_DELETED: 'ERROR-CONTRIBUTOR-0001',

  // Address
  ADDRESS_ERROR_NOT_FOUND: 'ERROR-ADDRESS-0000',
  ADDRESS_ERROR_INVALID: 'ERROR-ADDRESS-0001',

  // Order
  ORDER_ERROR_NOT_FOUND: 'ERROR-ORDER-0000',
  ORDER_ERROR_INVALID_STATUS: 'ERROR-ORDER-0001',
  ORDER_ERROR_CANNOT_CANCEL: 'ERROR-ORDER-0002',

  //Coupon
  COUPON_ERROR_NOT_FOUND: 'ERROR-COUPON-0000',
  COUPON_ERROR_CODE_EXISTED: 'ERROR-COUPON-0001',
  COUPON_ERROR_INVALID: 'ERROR-COUPON-0002',

  // Favorite product
  FAVORITE_PRODUCT_ERROR_NOT_FOUND: 'ERROR-FAVORITE-PRODUCT-0000',
  FAVORITE_PRODUCT_ERROR_EXISTS: 'ERROR-FAVORITE-PRODUCT-0001',

  // Viewed product
  VIEWED_PRODUCT_ERROR_NOT_FOUND: 'ERROR-VIEWED-PRODUCT-0000'
} as const;
